### ISSUE TITLE
Thrown Weapons and Firearms crash the server

### ISSUE THREAD

**Issue by Beanzilla** [Beanzilla/rangedweapons-1#1]
Looks like the same issues with the guns needs to be "fixed" with the thrown weapons too.

**Comment by Beanzilla** [comment]
I see in the server logs a lot of using undefined variables... and keep running into crashes where we try to use some undefined variable. (Might be what is breaking the server)

**Comment by IvanTurgenev** [comment]
Any more tests on these?

**Comment by Beanzilla** [comment]
Checkout the dev branch... gives a direct issue... rather is the latest that I was working on. (I haven't been in touch on this repo in a while)

**Comment by Beanzilla** [comment]
Thank you for the PR fixing this.

> Sorry I've just been working on my mods, completely forgot about this mod.
